[workspace]
members = ["crates/remote-merge", "crates/remote-merge-core", "crates/remote-merge-protocol", "crates/remote-merge-settings", "crates/remote-merge-ssh", "crates/remote-merge-config", "crates/remote-merge-agent", "crates/remote-merge-engine"]
default-members = ["crates/remote-merge", "crates/remote-merge-core", "crates/remote-merge-protocol", "crates/remote-merge-settings", "crates/remote-merge-ssh", "crates/remote-merge-config", "crates/remote-merge-agent", "crates/remote-merge-engine"]
resolver = "2"

[profile.release]
strip = true
