[package]
name = "remote-merge-ssh"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
remote-merge-settings = { path = "../remote-merge-settings" }
rpassword = "7"
zeroize = "1"
remote-merge-core = { path = "../remote-merge-core" }
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"

[dev-dependencies]
serial_test = "3"
tempfile = "3"
